name: Python Greet Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run pylint
        run: |
          pylint greet_git.py --disable=C0114,C0116,W0612
      - name: Run greet script
        run: |
          python greet_git.py
